import { ALL_CLAIMS, FACE_SHORT, evaluateHand, compareClaims } from "./rules.js";
import { PhotonDiceRoom } from "./photon-room.js";

const $=selector=>document.querySelector(selector);
const ui={join:$("#join-dialog"),form:$("#join-form"),name:$("#player-name"),code:$("#room-code"),error:$("#join-error"),app:$("#app"),room:$("#room-label"),connection:$("#connection"),lobby:$("#lobby"),game:$("#game"),results:$("#results"),modeButtons:[...document.querySelectorAll("[data-mode]")],liarOptions:$("#liar-options"),rerollButtons:[...document.querySelectorAll("[data-rerolls]")],start:$("#start-game"),hostNote:$("#host-note"),lobbyPlayers:$("#lobby-players"),playerCount:$("#player-count"),phaseKicker:$("#phase-kicker"),status:$("#game-status"),claimStatus:$("#claim-status"),dice:$("#dice"),cup:$("#cup"),hand:$("#hand-label"),decision:$("#decision-controls"),accept:$("#accept-dice"),challenge:$("#call-liar"),play:$("#play-controls"),rollInfo:$("#roll-info"),roll:$("#roll-dice"),finish:$("#finish-hand"),claim:$("#claim-controls"),claimCategory:$("#claim-category"),claimDetail:$("#claim-detail"),claimPreview:$("#claim-preview"),makeClaim:$("#make-claim"),reveal:$("#reveal"),revealTitle:$("#reveal-title"),revealCopy:$("#reveal-copy"),gamePlayers:$("#game-players"),turnCounter:$("#turn-counter"),winner:$("#winner"),scores:$("#scores"),returnLobby:$("#return-lobby"),menu:$("#menu"),menuButton:$("#menu-button"),closeMenu:$("#close-menu"),invite:$("#invite"),leave:$("#leave-table"),rules:$("#rules-copy"),toast:$("#toast"),install:$("#install")};
let room=null,snapshot=null,privateHand=null,lastDiceValues="",deferredInstall=null;
const params=new URLSearchParams(location.search);ui.code.value=params.get("room")||"ROYAL";ui.name.value=localStorage.getItem("poker-dice-name")||"";ui.join.showModal();

ui.form.addEventListener("submit",async event=>{event.preventDefault();ui.error.textContent="";const button=ui.form.querySelector("button");button.disabled=true;try{const name=ui.name.value.trim()||"Player",code=ui.code.value.trim()||"ROYAL";localStorage.setItem("poker-dice-name",name);room=new PhotonDiceRoom(window.APP_CONFIG||{});wireRoom(room);await room.connect({roomCode:code,name});history.replaceState(null,"",`${location.pathname}?room=${encodeURIComponent(room.roomCode)}`);ui.room.textContent=`TABLE ${room.roomCode}`;ui.join.close();ui.app.hidden=false;}catch(error){ui.error.textContent=error.message;room?.disconnect();room=null;}finally{button.disabled=false;}});
function wireRoom(next){next.addEventListener("status",({detail})=>{ui.connection.textContent=friendlyStatus(detail);ui.connection.classList.toggle("live",detail==="Connected");});next.addEventListener("error",({detail})=>{ui.error.textContent=detail;toast(detail);});next.addEventListener("snapshot",({detail})=>{snapshot=detail;render();});next.addEventListener("private-hand",({detail})=>{privateHand=detail;render();});}

ui.modeButtons.forEach(button=>button.addEventListener("click",()=>room?.command("settings",{mode:button.dataset.mode})));ui.rerollButtons.forEach(button=>button.addEventListener("click",()=>room?.command("settings",{rerolls:Number(button.dataset.rerolls)})));ui.start.addEventListener("click",()=>{unlockAudio();room?.command("start");});ui.roll.addEventListener("click",()=>{unlockAudio();playSound("roll");if(snapshot.mode==="poker")room.command("poker-roll");else room.command("liar-roll",{held:privateHand?.held||[false,false,false,false,false]});});ui.finish.addEventListener("click",()=>room?.command("poker-finish"));ui.accept.addEventListener("click",()=>{playSound("cup");room?.command("liar-accept");});ui.challenge.addEventListener("click",()=>{playSound("challenge");room?.command("liar-challenge");});ui.makeClaim.addEventListener("click",()=>{const key=ui.claimDetail.value;if(key){playSound("claim");room?.command("liar-claim",{key});}});ui.returnLobby.addEventListener("click",()=>room?.command("return-lobby"));
ui.dice.addEventListener("click",event=>{const die=event.target.closest(".die");if(!die||!snapshot||String(snapshot.currentActor)!==String(room.myActor()))return;const index=Number(die.dataset.index);if(snapshot.mode==="poker")room.command("poker-hold",{index});else if(snapshot.liarStage==="play")room.command("liar-hold",{index});});
ui.claimCategory.addEventListener("change",populateClaimDetails);ui.claimDetail.addEventListener("change",updateClaimPreview);
ui.menuButton.addEventListener("click",()=>ui.menu.showModal());ui.closeMenu.addEventListener("click",()=>ui.menu.close());ui.leave.addEventListener("click",()=>{room?.disconnect();location.href=location.pathname;});ui.invite.addEventListener("click",invite);

function render(){if(!snapshot||!room)return;const me=snapshot.players[String(room.myActor())],isHost=String(snapshot.host)===String(room.myActor()),isTurn=String(snapshot.currentActor)===String(room.myActor()),spectator=!me||me.spectator||me.eliminated;ui.lobby.hidden=snapshot.phase!=="lobby";ui.game.hidden=snapshot.phase==="lobby"||snapshot.phase==="results";ui.results.hidden=snapshot.phase!=="results";
  if(snapshot.phase==="lobby")renderLobby(isHost);else if(snapshot.phase==="results")renderResults(isHost);else renderGame({me,isHost,isTurn,spectator});renderPlayers(ui.lobbyPlayers,false);renderPlayers(ui.gamePlayers,true);}
function renderLobby(isHost){ui.modeButtons.forEach(button=>{button.classList.toggle("selected",button.dataset.mode===snapshot.mode);button.disabled=!isHost;});ui.liarOptions.hidden=snapshot.mode!=="liar";ui.rerollButtons.forEach(button=>{button.classList.toggle("selected",Number(button.dataset.rerolls)===snapshot.settings.rerolls);button.disabled=!isHost;});const count=activePlayers().length;ui.playerCount.textContent=count;ui.start.disabled=!isHost||count<2;ui.start.textContent=`Start ${snapshot.mode==="liar"?"Liar’s Dice":"Poker Dice"}`;ui.hostNote.textContent=isHost?(count<2?"One more player is needed.":"You are the host. Settings lock when play begins."):`${snapshot.players[snapshot.host]?.name||"The host"} is choosing the rules.`;}
function renderGame({me,isTurn,spectator}){const current=snapshot.players[snapshot.currentActor];ui.phaseKicker.textContent=snapshot.phase==="liar-reveal"?"REVEALED":spectator?"SPECTATING":isTurn?"YOUR TURN":`TURN · ${current?.name||"Player"}`;ui.turnCounter.textContent=snapshot.mode==="liar"?`ROUND ${snapshot.round}`:`${snapshot.order.indexOf(snapshot.currentActor)+1}/${snapshot.order.length}`;ui.claimStatus.textContent=snapshot.currentClaim?`${snapshot.currentClaim.player} claims ${snapshot.currentClaim.label}`:"";ui.decision.hidden=true;ui.play.hidden=true;ui.claim.hidden=true;ui.reveal.hidden=true;
  let visibleDice=null,held=null;if(snapshot.mode==="poker"){visibleDice=snapshot.dice;held=snapshot.held;ui.status.textContent=isTurn?`Your roll ${snapshot.rollsUsed}/3`:`${current?.name||"Someone"} is rolling`;ui.hand.textContent=snapshot.rollsUsed?evaluateHand(visibleDice).label:"The table is waiting";ui.play.hidden=!isTurn;ui.rollInfo.textContent=snapshot.rollsUsed?`${3-snapshot.rollsUsed} roll${3-snapshot.rollsUsed===1?"":"s"} remaining · tap dice to hold`:"Roll all five dice";ui.roll.hidden=snapshot.rollsUsed>=3;ui.finish.hidden=snapshot.rollsUsed<1||snapshot.rollsUsed>=3;}
  else if(snapshot.phase==="liar-reveal"){visibleDice=snapshot.reveal?.dice;ui.status.textContent="The cup is lifted";ui.hand.textContent=snapshot.reveal?.actual?.label||"Revealed";ui.reveal.hidden=false;ui.revealTitle.textContent=snapshot.reveal?.trueClaim?"The claim survives.":"Caught lying.";ui.revealCopy.textContent=`${snapshot.reveal?.loserName||"A player"} is eliminated. Next round in five seconds.`;}
  else{const canSee=isTurn&&snapshot.liarStage==="play"&&privateHand;visibleDice=canSee?privateHand.dice:null;held=canSee?privateHand.held:null;const mayRaise=legalClaims().length>0;ui.status.textContent=snapshot.liarStage==="decision"?(isTurn?(mayRaise?"Believe them?":"There is nowhere left to raise"):"A decision is being made"):(isTurn?"Build it—or bluff it":"The dice are concealed");ui.hand.textContent=visibleDice?evaluateHand(visibleDice).label:"Only the active player can see the hand";ui.decision.hidden=!(isTurn&&snapshot.liarStage==="decision");ui.accept.disabled=!mayRaise;ui.accept.textContent=mayRaise?"Accept dice":"Maximum claim · call liar";ui.play.hidden=!(isTurn&&snapshot.liarStage==="play");ui.claim.hidden=!(isTurn&&snapshot.liarStage==="play");if(!ui.claim.hidden)populateClaimCategories();ui.rollInfo.textContent=privateHand?`${Math.max(0,snapshot.settings.rerolls-privateHand.rollsUsed)} reroll${snapshot.settings.rerolls-privateHand.rollsUsed===1?"":"s"} remaining · tap dice to hold`:"";ui.roll.hidden=!privateHand||privateHand.rollsUsed>=snapshot.settings.rerolls;ui.finish.hidden=true;}
  renderDice(visibleDice,held);ui.cup.hidden=Boolean(visibleDice);}
function renderDice(values,held){ui.dice.innerHTML=values?values.map((value,index)=>`<button class="die ${held?.[index]?"held":""}" data-index="${index}" aria-label="${FACE_SHORT[value]}${held?.[index]?", held":""}"><img src="textures/face${value}.png" alt="${FACE_SHORT[value]}"></button>`).join(""):"";const valuesSignature=values?values.join(""):"hidden";if(values&&valuesSignature!==lastDiceValues){lastDiceValues=valuesSignature;animateDice();}else if(!values){lastDiceValues="hidden";}}
function animateDice(){requestAnimationFrame(()=>{[...ui.dice.children].forEach((die,index)=>{setTimeout(()=>die.classList.add("rolling"),index*45);setTimeout(()=>die.classList.remove("rolling"),850+index*45);});});}
function renderPlayers(container,inGame){if(!snapshot)return;const ids=Object.keys(snapshot.players).filter(id=>snapshot.players[id].connected);container.innerHTML=ids.map(id=>{const p=snapshot.players[id],current=id===String(snapshot.currentActor),me=id===String(room.myActor()),state=p.eliminated?"Eliminated":p.spectator?"Spectating":inGame&&snapshot.mode==="poker"&&p.finalHand?p.finalHand.label:current?"Playing":"Ready";return `<div class="player ${current?"current":""} ${p.eliminated?"eliminated":""}"><strong>${escapeHtml(p.name)}${me?" · you":""}</strong><small>${escapeHtml(state)}</small>${id===String(snapshot.host)?'<span class="badge">HOST</span>':""}</div>`;}).join("")||'<p class="tiny">Waiting for players</p>';}
function renderResults(isHost){const active=activePlayers();if(snapshot.mode==="liar"){const winner=active[0];ui.winner.textContent=winner?`${winner.name} tells the last convincing lie.`:"Nobody survived the table.";ui.scores.innerHTML=Object.values(snapshot.players).filter(p=>snapshot.order.includes(p.id)).map(p=>`<div class="score-row"><span>${escapeHtml(p.name)}</span><b>${p.eliminated?"OUT":"WINNER"}</b></div>`).join("");}else{const ranked=Object.values(snapshot.players).filter(p=>p.finalHand).sort((a,b)=>compareHandObjects(b.finalHand,a.finalHand));ui.winner.textContent=ranked[0]?`${ranked[0].name} wins with ${ranked[0].finalHand.label}.`:"Game over";ui.scores.innerHTML=ranked.map((p,i)=>`<div class="score-row"><span>${i+1}. ${escapeHtml(p.name)}</span><b>${escapeHtml(p.finalHand.label)}</b></div>`).join("");}ui.returnLobby.hidden=!isHost;}
function populateClaimCategories(){const legal=legalClaims();const kinds=[...new Set(legal.map(c=>c.kind))];const previous=ui.claimCategory.value;ui.claimCategory.innerHTML=kinds.map(kind=>`<option value="${kind}">${categoryName(kind)}</option>`).join("");if(kinds.includes(previous))ui.claimCategory.value=previous;populateClaimDetails();ui.makeClaim.disabled=!legal.length;}
function populateClaimDetails(){const legal=legalClaims().filter(c=>c.kind===ui.claimCategory.value);ui.claimDetail.innerHTML=legal.map(c=>`<option value="${c.key}">${escapeHtml(c.label)}</option>`).join("");updateClaimPreview();}
function updateClaimPreview(){const item=ALL_CLAIMS.find(c=>c.key===ui.claimDetail.value);ui.claimPreview.textContent=item?`You are claiming: ${item.label}`:"No higher claim remains. Call it next time.";ui.makeClaim.disabled=!item;}
function legalClaims(){return ALL_CLAIMS.filter(claim=>!snapshot.currentClaim||compareClaims(claim,snapshot.currentClaim)>0);}
function categoryName(kind){return ({bust:"High Card",pair:"One Pair","two-pair":"Two Pair",trips:"Three of a Kind","low-straight":"Low Straight","high-straight":"High Straight","full-house":"Full House",quads:"Four of a Kind",five:"Five of a Kind"})[kind]||kind;}
function activePlayers(){return snapshot.order.map(id=>snapshot.players[id]).filter(p=>p?.connected&&!p.spectator&&!p.eliminated);}
function compareHandObjects(a,b){if(a.rank!==b.rank)return a.rank-b.rank;for(let i=0;i<Math.max(a.vector.length,b.vector.length);i++){if((a.vector[i]||0)!==(b.vector[i]||0))return(a.vector[i]||0)-(b.vector[i]||0);}return 0;}
async function invite(){const url=location.href,share={title:"Poker Dice",text:`Join my Poker Dice table ${room.roomCode}`,url};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(url);toast("Table link copied");}}catch(error){if(error.name!=="AbortError")toast("Copy the address from your browser");}}
function friendlyStatus(value){if(value==="Connected")return"Live";if(/connect/i.test(value))return"Connecting";return value;}
function toast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>ui.toast.classList.remove("show"),2400);}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);}

ui.rules.innerHTML='<p><b>Poker Dice:</b> each player gets up to three rolls. Tap dice to hold them. The strongest poker hand wins.</p><p><b>Liar’s Dice:</b> accept the concealed hand or call the previous claim. If you accept, use the configured rerolls, then make a strictly higher claim. A failed liar call eliminates either the claimant or challenger. Last player standing wins.</p>';
addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstall=event;ui.install.hidden=false;});ui.install.addEventListener("click",async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;ui.install.hidden=true;}});if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
let audioContext=null;function unlockAudio(){audioContext||=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume?.();}function playSound(kind){try{unlockAudio();const now=audioContext.currentTime,osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain).connect(audioContext.destination);const map={roll:[130,55,.22],cup:[85,42,.18],challenge:[310,105,.34],claim:[210,390,.16]},[from,to,duration]=map[kind]||map.roll;osc.type=kind==="challenge"?"sawtooth":"triangle";osc.frequency.setValueAtTime(from,now);osc.frequency.exponentialRampToValueAtTime(to,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.14,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.start(now);osc.stop(now+duration+.02);}catch{}}
