export class BuzzerModel {
  constructor(){this.revision=0;this.players={};this.gameState="LOBBY";this.hostId=null;this.questionNumber=0;this.currentCorrectAnswer=null;this.lastRoundCorrectAnswer=null}
  join(id,name="Player"){const key=String(id);if(!this.players[key])this.players[key]={id:Number(id),name:cleanName(name),score:0,currentAnswer:null,lastAnswerCorrect:null,lastAnswerSubmitted:null};else this.players[key].name=cleanName(name);return this.changed()}
  leave(id){const key=String(id),wasHost=Number(this.hostId)===Number(id);delete this.players[key];if(wasHost){this.hostId=Object.keys(this.players).map(Number).sort((a,b)=>a-b)[0]??null;if(this.hostId===null)this.resetState()}return this.changed()}
  command(actor,type,value){actor=Number(actor);const player=this.players[String(actor)];if(!player)return false;const isHost=actor===Number(this.hostId);switch(type){case"claimHost":if(this.hostId!==null)return false;this.hostId=actor;break;case"startGame":if(!isHost||this.gameState!=="LOBBY"||Object.keys(this.players).length<2)return false;this.nextRound();break;case"setAnswer":if(!isHost||this.gameState!=="QUESTION_SETUP"||typeof value!=="boolean")return false;this.currentCorrectAnswer=value;this.gameState="TAKING_ANSWERS";break;case"playerAnswer":if(isHost||this.gameState!=="TAKING_ANSWERS"||player.currentAnswer!==null||typeof value!=="boolean")return false;player.currentAnswer=value;break;case"nextQuestion":if(!isHost||this.gameState!=="TAKING_ANSWERS")return false;this.scoreRound();this.nextRound();break;case"endGame":if(!isHost||!["QUESTION_SETUP","TAKING_ANSWERS"].includes(this.gameState))return false;this.gameState="GAME_OVER";break;case"resetGame":if(!isHost)return false;this.resetState();break;default:return false}return this.changed()}
  scoreRound(){this.lastRoundCorrectAnswer=this.currentCorrectAnswer;for(const player of Object.values(this.players)){player.lastAnswerSubmitted=player.currentAnswer;player.lastAnswerCorrect=player.currentAnswer===null?null:player.currentAnswer===this.currentCorrectAnswer;if(player.lastAnswerCorrect)player.score++}}
  nextRound(){this.questionNumber++;this.currentCorrectAnswer=null;for(const player of Object.values(this.players))player.currentAnswer=null;this.gameState="QUESTION_SETUP"}
  resetState(){this.hostId=null;this.questionNumber=0;this.currentCorrectAnswer=null;this.lastRoundCorrectAnswer=null;this.gameState="LOBBY";for(const player of Object.values(this.players))Object.assign(player,{score:0,currentAnswer:null,lastAnswerCorrect:null,lastAnswerSubmitted:null})}
  changed(){this.revision++;return true}
  snapshot(){return structuredClone({revision:this.revision,players:this.players,gameState:this.gameState,hostId:this.hostId,questionNumber:this.questionNumber,currentCorrectAnswer:this.currentCorrectAnswer,lastRoundCorrectAnswer:this.lastRoundCorrectAnswer})}
  restore(state){if(state){Object.assign(this,structuredClone(state));this.players||={}}}
}
function cleanName(value){return String(value||"Player").trim().replace(/\s+/g," ").slice(0,20)||"Player"}
