import{BuzzerModel}from"./game-model.js";const EVENT={HELLO:1,COMMAND:2,SNAPSHOT:3,REQUEST_STATE:4},STATE_PROPERTY="buzzer_state",NAME_PROPERTY="buzzer_name";
export class PhotonRoom extends EventTarget{
constructor(config){super();this.config=config;this.connected=false;this.model=null;this.latest=null}
async connect({roomCode,name}){if(!this.config.PHOTON_APP_ID)throw new Error("Add PHOTON_APP_ID to config.js first.");await loadScript(this.config.PHOTON_SDK_URL||"vendor/photon.min.js");const Photon=window.Photon;if(!Photon?.LoadBalancing)throw new Error("Photon Realtime SDK did not load.");this.roomCode=normalizeRoom(roomCode);this.name=String(name).trim().slice(0,20)||"Player";const Client=Photon.LoadBalancing.LoadBalancingClient;this.client=new Client(Photon.ConnectionProtocol.Wss,this.config.PHOTON_APP_ID,"buzzer-2");this.client.setUserId(loadIdentity());this.client.setLogLevel(this.config.DEBUG?Photon.LogLevel.DEBUG:Photon.LogLevel.WARN);this.client.onStateChange=state=>{this.status(Client.StateToName?.(state)||String(state));if(state===Client.State.JoinedLobby)this.client.joinRoom(this.roomCode,{createIfNotExists:true},{isVisible:false,maxPlayers:40,playerTTL:5000,roomTTL:300000});if(state===Client.State.Disconnected){this.connected=false;this.status("Disconnected")}};this.client.onJoinRoom=created=>this.onJoinRoom(created);this.client.onActorJoin=actor=>this.onActorJoin(actor);this.client.onActorLeave=actor=>this.onActorLeave(actor);this.client.onActorPropertiesChange=()=>this.emitPresence();this.client.onMyRoomPropertiesChange=()=>{if(!this.isMaster())this.consumeRoomState()};this.client.onEvent=(code,content,actor)=>this.onEvent(code,content,actor);this.client.onError=(_code,message)=>this.error(message||"Photon connection error");return new Promise((resolve,reject)=>{this.resolveConnect=resolve;this.rejectConnect=reject;this.timeout=setTimeout(()=>reject(new Error("Photon connection timed out.")),20000);this.client.connectToNameServer({region:this.config.PHOTON_REGION||"eu"})})}
onJoinRoom(created){clearTimeout(this.timeout);this.connected=true;this.client.myActor().setName(this.name);this.client.myActor().setCustomProperty(NAME_PROPERTY,this.name);if(created){this.model=new BuzzerModel();this.model.join(this.myActor(),this.name);this.broadcast()}else if(this.isMaster()){this.consumeRoomState();this.model||=new BuzzerModel();this.rebuildPlayers();this.broadcast()}else{this.client.raiseEvent(EVENT.HELLO,{name:this.name},{targetActors:[this.client.myRoomMasterActorNr()]});this.client.raiseEvent(EVENT.REQUEST_STATE,null,{targetActors:[this.client.myRoomMasterActorNr()]})}this.status("Connected");this.emitPresence();this.resolveConnect?.();this.resolveConnect=null}
onActorJoin(actor){if(this.isMaster()&&this.model){const existing=this.model.players[String(actor.actorNr)];this.model.join(actor.actorNr,actor.getCustomProperty(NAME_PROPERTY)||existing?.name||actor.name||`Player ${actor.actorNr}`);this.broadcast()}this.emitPresence()}
onActorLeave(actor){if(this.isMaster()&&this.model){this.model.leave(actor.actorNr);this.broadcast()}setTimeout(()=>{if(this.connected&&this.isMaster()&&!this.model){this.consumeRoomState();this.model||=new BuzzerModel();this.rebuildPlayers();this.broadcast()}},100);this.emitPresence()}
onEvent(code,content,actor){if(code===EVENT.HELLO&&this.isMaster()){this.model.join(actor,content?.name);this.broadcast()}else if(code===EVENT.COMMAND&&this.isMaster()){if(this.model.command(actor,content?.type,content?.value))this.broadcast()}else if(code===EVENT.SNAPSHOT&&!this.isMaster())this.consumeSnapshot(content);else if(code===EVENT.REQUEST_STATE&&this.isMaster())this.broadcast(actor)}
command(type,value=null){if(!this.connected)return;if(this.isMaster()){if(this.model.command(this.myActor(),type,value))this.broadcast()}else this.client.raiseEvent(EVENT.COMMAND,{type,value},{targetActors:[this.client.myRoomMasterActorNr()]})}
rebuildPlayers(){const actors=this.client.myRoomActors(),present=new Set(Object.keys(actors).map(Number));for(const id of Object.keys(this.model.players).map(Number))if(!present.has(id))this.model.leave(id);for(const id of present){const actor=actors[id];this.model.join(id,actor?.getCustomProperty(NAME_PROPERTY)||actor?.name||`Player ${id}`)}}
broadcast(target=null){if(!this.model||!this.connected||!this.isMaster())return;const snapshot=this.model.snapshot();this.consumeSnapshot(snapshot);this.client.myRoom().setCustomProperty(STATE_PROPERTY,JSON.stringify(snapshot));this.client.raiseEvent(EVENT.SNAPSHOT,snapshot,target?{targetActors:[target]}:{receivers:window.Photon.LoadBalancing.Constants.ReceiverGroup.Others})}
consumeRoomState(){const raw=this.client.myRoom().getCustomProperty(STATE_PROPERTY);if(!raw)return;try{const state=typeof raw==="string"?JSON.parse(raw):raw;if(this.isMaster()){this.model=new BuzzerModel();this.model.restore(state)}this.consumeSnapshot(state)}catch(error){this.error(`Could not restore room: ${error.message}`)}}
consumeSnapshot(state){if(!state||(this.latest&&state.revision<this.latest.revision))return;this.latest=state;this.dispatchEvent(new CustomEvent("snapshot",{detail:state}))}
emitPresence(){if(!this.client?.myRoomActors)return;this.dispatchEvent(new CustomEvent("presence",{detail:Object.values(this.client.myRoomActors()).map(actor=>({actor:actor.actorNr,name:actor.getCustomProperty(NAME_PROPERTY)||actor.name||`Player ${actor.actorNr}`}))}))}
myActor(){return this.client.myActor().actorNr}isMaster(){return this.client&&this.myActor()===this.client.myRoomMasterActorNr()}status(message){this.dispatchEvent(new CustomEvent("status",{detail:message}))}error(message){this.dispatchEvent(new CustomEvent("error",{detail:message}));this.rejectConnect?.(new Error(message))}disconnect(){this.client?.disconnect()}}
function normalizeRoom(value){return String(value||"").toUpperCase().replace(/[^A-Z]/g,"").slice(0,5)}function loadIdentity(){let id=localStorage.getItem("buzzer-photon-id");if(!id){id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem("buzzer-photon-id",id)}return id}async function loadScript(url){if(window.Photon?.LoadBalancing)return;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=url;script.onload=resolve;script.onerror=()=>reject(new Error(`Could not load ${url}`));document.head.append(script)})}
