export class AudioEngine {
  constructor(){this.enabled=localStorage.getItem("breakpong-audio")!=="off";this.ctx=null;this.ambience=null}
  async unlock(){if(!this.enabled)return;this.ctx||=new(window.AudioContext||window.webkitAudioContext)();if(!this.master)this.buildMix();if(this.ctx.state==="suspended")await this.ctx.resume();this.startAmbience()}
  buildMix(){const c=this.ctx;this.master=c.createGain();this.master.gain.value=.82;this.compressor=c.createDynamicsCompressor();this.compressor.threshold.value=-18;this.compressor.knee.value=10;this.compressor.ratio.value=5;this.compressor.attack.value=.004;this.compressor.release.value=.22;this.dry=c.createGain();this.dry.gain.value=.92;this.wet=c.createGain();this.wet.gain.value=.58;this.reverb=c.createConvolver();this.reverb.buffer=this.makeImpulse(2.7,2.25);this.dry.connect(this.compressor);this.reverb.connect(this.wet).connect(this.compressor);this.compressor.connect(this.master).connect(c.destination)}
  makeImpulse(seconds,decay){const length=Math.floor(this.ctx.sampleRate*seconds),buffer=this.ctx.createBuffer(2,length,this.ctx.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);for(let i=0;i<length;i++){const early=i<.09*this.ctx.sampleRate&&(Math.random()>.985)?1:0;data[i]=((Math.random()*2-1)*Math.pow(1-i/length,decay)+early*.45)*.72}}return buffer}
  route(node,send=.45){node.connect(this.dry);const verb=this.ctx.createGain();verb.gain.value=send;node.connect(verb).connect(this.reverb)}
  toggle(){this.enabled=!this.enabled;localStorage.setItem("breakpong-audio",this.enabled?"on":"off");if(this.enabled)this.unlock();else this.stopAmbience();return this.enabled}
  cue(name){if(!this.enabled||!this.ctx)return;const sounds={paddle:()=>this.metalHit(185,.13,.18),brick:()=>this.metalHit(360,.09,.12),black:()=>this.heavyThud(42,.82,.28),power:()=>{this.sweep(180,920,.48,.11,.72);this.shimmer(620,.5,.06)},portal:()=>this.portalSwoosh(),score:()=>{this.heavyThud(54,.62,.19);setTimeout(()=>this.sweep(170,510,.5,.1,.72),85)},countdown:()=>this.tone(480,.1,"sine",.08,420,.55),start:()=>this.ballLaunch(),launch:()=>{this.heavyThud(46,.72,.24);this.metalHit(95,.32,.1)},land:()=>this.heavyThud(34,.95,.32),machinery:()=>{this.sweep(48,118,1.15,.11,.8);this.noise(.7,.07,520,.82)},matchpoint:()=>this.matchAlarm()};sounds[name]?.()}
  tone(freq,duration,type="sine",volume=.1,endFreq=freq,send=.45,delay=0){const t=this.ctx.currentTime+delay,osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),t+duration);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(volume,t+.006);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);this.route(gain,send);osc.start(t);osc.stop(t+duration+.03)}
  sweep(from,to,duration,volume,send){this.tone(from,duration,"sine",volume,to,send)}
  noise(duration,volume,cutoff,send=.5,delay=0){const frames=Math.ceil(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,frames,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/frames,1.7);const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();source.buffer=buffer;filter.type="lowpass";filter.frequency.value=cutoff;gain.gain.value=volume;source.connect(filter).connect(gain);this.route(gain,send);source.start(this.ctx.currentTime+delay)}
  metalHit(freq,duration,volume){this.tone(freq,duration,"square",volume,freq*.58,.68);this.tone(freq*2.73,duration*.72,"triangle",volume*.5,freq*1.2,.82,.006);this.tone(freq*4.17,duration*.42,"sine",volume*.3,freq*2,.9,.012);this.noise(duration*.9,volume*.35,2600,.7)}
  heavyThud(freq,duration,volume){this.tone(freq,duration,"sine",volume,22,.82);this.tone(freq*1.9,duration*.42,"triangle",volume*.42,31,.75,.008);this.noise(.28,volume*.52,230,.72)}
  ballLaunch(){this.metalHit(125,.18,.16);this.sweep(72,260,.24,.1,.72);this.noise(.13,.055,1700,.55)}
  portalSwoosh(){const duration=.62,frames=Math.ceil(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,frames,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++){const p=i/frames,envelope=Math.sin(Math.PI*p);data[i]=(Math.random()*2-1)*envelope}const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain(),t=this.ctx.currentTime;source.buffer=buffer;filter.type="bandpass";filter.Q.value=1.1;filter.frequency.setValueAtTime(260,t);filter.frequency.exponentialRampToValueAtTime(2800,t+.24);filter.frequency.exponentialRampToValueAtTime(420,t+duration);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.2,t+.09);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(filter).connect(gain);this.route(gain,.92);source.start(t);this.sweep(82,720,.3,.12,.9);this.tone(540,.42,"sine",.055,120,.92,.16)}
  shimmer(freq,duration,volume){for(let i=0;i<4;i++)this.tone(freq*(1+i*.38),duration*(1-i*.1),"sine",volume/(i+1),freq*(.8+i*.3),.88,i*.018)}
  matchAlarm(){this.tone(92,.44,"sawtooth",.12,76,.75);this.tone(184,.35,"square",.06,138,.8,.08);setTimeout(()=>{if(this.enabled&&this.ctx)this.tone(116,.5,"sawtooth",.11,82,.78)},330)}
  startAmbience(){if(this.ambience||!this.ctx)return;const gain=this.ctx.createGain(),low=this.ctx.createOscillator(),motor=this.ctx.createOscillator();low.type="sine";low.frequency.value=38;motor.type="triangle";motor.frequency.value=61;gain.gain.value=.018;low.connect(gain);motor.connect(gain);this.route(gain,.7);low.start();motor.start();this.ambience={gain,low,motor}}
  stopAmbience(){if(!this.ambience)return;this.ambience.low.stop();this.ambience.motor.stop();this.ambience=null}
}
