import { ArenaView } from "./arena-view.js?v=20260813-5";
import { PhotonRoom } from "./photon-room.js?v=20260813-5";
import { AudioEngine } from "./audio-engine.js?v=20260813-5";
const BUILD_ID="20260813-5";
const $=(id)=>document.getElementById(id);const ui={lobby:$("lobby"),form:$("join-form"),name:$("display-name"),code:$("room-code"),error:$("join-error"),status:$("connection-status"),score:$("score"),message:$("game-message"),p1:$("player-1"),p2:$("player-2"),panel:$("room-panel"),room:$("room-label"),role:$("role-label"),spectator:$("spectator-badge")};
const audio=new AudioEngine();const view=new ArenaView($("arena"));view.onCue=(name)=>audio.cue(name);let room=null,presence=[];const params=new URLSearchParams(location.search);ui.code.value=params.get("room")||"ARENA";ui.name.value=localStorage.getItem("breakpong-name")||"";ui.lobby.showModal();
ui.form.addEventListener("submit",async(event)=>{event.preventDefault();await audio.unlock();ui.error.textContent="";ui.form.querySelector("button").disabled=true;try{localStorage.setItem("breakpong-name",ui.name.value.trim());room=new PhotonRoom(window.APP_CONFIG||{});wireRoom(room);await room.connect({roomCode:ui.code.value,name:ui.name.value});history.replaceState(null,"",`${location.pathname}?room=${encodeURIComponent(room.roomCode)}&v=${BUILD_ID}`);ui.room.textContent=room.roomCode;ui.panel.hidden=true;ui.lobby.close()}catch(error){ui.error.textContent=error.message;room?.disconnect();room=null}finally{ui.form.querySelector("button").disabled=false}});
function wireRoom(next){next.addEventListener("status",({detail})=>{ui.status.textContent=detail;document.body.classList.toggle("connected",detail==="Connected")});next.addEventListener("error",({detail})=>ui.error.textContent=detail);next.addEventListener("presence",({detail})=>{presence=detail;renderPlayers(next.latest)});next.addEventListener("snapshot",({detail})=>{view.update(detail);render(detail)})}
function render(state){ui.score.innerHTML=`${state.score[1]} <i>:</i> ${state.score[2]}`;const role=room.role(),spectating=role==="Spectator";ui.role.textContent=role;ui.spectator.hidden=!spectating;document.body.classList.toggle("spectator",spectating);renderPlayers(state);const messages={waiting:"Waiting for two players",disconnected:"Player left — holding the arena",serving_paused:`Player ${state.servingPlayer} serves`,won1:"Player 1 wins!",won2:"Player 2 wins!"};ui.message.textContent=state.state==="countdown"?`Game starts in ${state.countdown}`:state.state==="playing"?"":messages[state.state]||""}
function renderPlayers(state){if(!state)return;const nameOf=(actor)=>presence.find((person)=>Number(person.actor)===Number(actor))?.name||(actor?`Player ${actor}`:"Waiting…");ui.p1.textContent=nameOf(state.players[1]);ui.p2.textContent=nameOf(state.players[2])}
const keys=new Set();let sent=null;const isEditing=(target)=>target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement||target?.isContentEditable;function sendDirection(){const direction=(keys.has("ArrowDown")||keys.has("KeyS")?1:0)-(keys.has("ArrowUp")||keys.has("KeyW")?1:0);if(direction!==sent){sent=direction;room?.setInput(direction)}}
addEventListener("keydown",(e)=>{if(isEditing(e.target))return;if(["ArrowUp","ArrowDown","KeyW","KeyS"].includes(e.code)){e.preventDefault();keys.add(e.code);sendDirection()}});addEventListener("keyup",(e)=>{if(isEditing(e.target))return;keys.delete(e.code);sendDirection()});addEventListener("blur",()=>{keys.clear();sendDirection()});
for(const[id,direction]of[["move-up",-1],["move-down",1]]){const button=$(id);const down=(e)=>{e.preventDefault();sent=direction;room?.setInput(direction)},up=()=>{sent=0;room?.setInput(0)};button.addEventListener("pointerdown",down);button.addEventListener("pointerup",up);button.addEventListener("pointercancel",up)}
$("audio-toggle").textContent=audio.enabled?"Sound on":"Sound off";$("audio-toggle").onclick=()=>{$("audio-toggle").textContent=audio.toggle()?"Sound on":"Sound off"};$("menu-button").onclick=()=>ui.panel.hidden=!ui.panel.hidden;$("copy-invite").onclick=async()=>{await navigator.clipboard.writeText(location.href);$("copy-invite").textContent="Copied!";setTimeout(()=>$("copy-invite").textContent="Copy invite",1500)};$("reset-game").onclick=()=>room?.reset();$("leave-room").onclick=()=>{room?.disconnect();room=null;document.body.classList.remove("connected");ui.panel.hidden=true;ui.lobby.showModal()};
